Desktop/pos/pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls,name="admin-site"),
    path('', include('posApp.urls')),
]

account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.account_login, name="login"),
    re_path(r'^register/?$', views.account_register, name="register"),
    re_path(r'^logout/?$', views.account_logout, name="logout"),
]

e_voting/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

def redirect_to_dashboard(request):
    """Helper view to handle the root URL redirection."""
    if not request.user.is_authenticated:
        return redirect(f"{reverse('account:login')}?next={request.path}")
    
    if request.user.user_type == '1':
        return redirect('administrator:adminDashboard')
    return redirect('voting:voterDashboard')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('administrator/', include(('administrator.urls', 'administrator'), namespace='administrator')),
    path('', include(('voting.urls', 'voting'), namespace='voting')),
    
    # Handle both with and without trailing slash for the root URL
    path('', login_required(redirect_to_dashboard), name='home'),
    path('/', login_required(redirect_to_dashboard)),
]

# Serve static and media files in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve static files in production
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.http import HttpResponseNotFound
from django.urls import path
from . import views

app_name = 'voting'  

urlpatterns = [
    path('', views.index, name='index'),
    path('ballot/fetch/', views.fetch_ballot, name='fetch_ballot'),
    path('dashboard/', views.dashboard, name='voterDashboard'),
    path('verify/', views.verify, name='voterVerify'),
    path('verify/otp', views.verify_otp, name='verify_otp'),
    path('otp/resend/', views.resend_otp, name='resend_otp'),
    path('ballot/vote', views.show_ballot, name='show_ballot'),
    path('ballot/vote/preview', views.preview_vote, name='preview_vote'),
    path('ballot/vote/submit', views.submit_ballot, name='submit_ballot'),
    path('favicon.ico', lambda x: HttpResponseNotFound()),  
]

account/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.contrib.auth.hashers import make_password
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = CustomUser(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("user_type", 1)
        extra_fields.setdefault("last_name", "System")
        extra_fields.setdefault("first_name", "Administrator")

        assert extra_fields["is_staff"]
        assert extra_fields["is_superuser"]
        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    USER_TYPE = ((1, "Admin"), (2, "Voter"))
    username = None  # Removed username, using email instead
    email = models.EmailField(unique=True)
    user_type = models.CharField(default=2, choices=USER_TYPE, max_length=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.last_name + " " + self.first_name

voting/models.py
from django.db import models
from account.models import CustomUser
# Create your models here.


class Voter(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female')
    ]
    
    ACADEMIC_LEVEL_CHOICES = [
        ('1', 'Level 1'),
        ('2', 'Level 2'),
        ('3', 'Level 3'),
        ('4', 'Level 4'),
        ('5', 'Level 5')
    ]
    
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    phone = models.CharField(max_length=11, unique=True)  # Used for OTP
    photo = models.ImageField(upload_to="voters_photos", null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    department = models.CharField(max_length=100, null=True, blank=True)
    academic_level = models.CharField(max_length=1, choices=ACADEMIC_LEVEL_CHOICES, null=True, blank=True)
    otp = models.CharField(max_length=10, null=True)
    verified = models.BooleanField(default=False)
    voted = models.BooleanField(default=False)
    otp_sent = models.IntegerField(default=0)  # Control how many OTPs are sent

    def __str__(self):
        return self.admin.last_name + ", " + self.admin.first_name


class Position(models.Model):
    name = models.CharField(max_length=50, unique=True)
    max_vote = models.IntegerField()
    priority = models.IntegerField()

    def __str__(self):
        return self.name


class Candidate(models.Model):
    fullname = models.CharField(max_length=50)
    photo = models.ImageField(upload_to="candidates")
    bio = models.TextField()
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    def __str__(self):
        return self.fullname


class Votes(models.Model):
    voter = models.ForeignKey(Voter, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)

account/forms.py
from django import forms
from .models import *


class FormSettings(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FormSettings, self).__init__(*args, **kwargs)
        # Here make some changes such as:
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'


class CustomUserForm(FormSettings):
    email = forms.EmailField(required=True)
    # email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput)

    widget = {
        'password': forms.PasswordInput(),
    }

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        if kwargs.get('instance'):
            instance = kwargs.get('instance').__dict__
            self.fields['password'].required = False
            for field in CustomUserForm.Meta.fields:
                self.fields[field].initial = instance.get(field)
            if self.instance.pk is not None:
                self.fields['password'].widget.attrs['placeholder'] = "Fill this only if you wish to update password"
        else:
            self.fields['first_name'].required = True
            self.fields['last_name'].required = True

    def clean_email(self, *args, **kwargs):
        formEmail = self.cleaned_data['email'].lower()
        if self.instance.pk is None:  # Insert
            if CustomUser.objects.filter(email=formEmail).exists():
                raise forms.ValidationError(
                    "The given email is already registered")
        else:  # Update
            dbEmail = self.Meta.model.objects.get(
                id=self.instance.pk).email.lower()
            if dbEmail != formEmail:  # There has been changes
                if CustomUser.objects.filter(email=formEmail).exists():
                    raise forms.ValidationError(
                        "The given email is already registered")
        return formEmail

    def clean_password(self):
        password = self.cleaned_data.get("password", None)
        if self.instance.pk is not None:
            if not password:
                # return None
                return self.instance.password

        return make_password(password)

    class Meta:
        model = CustomUser
        fields = ['last_name', 'first_name', 'email', 'password', ]

voting/forms.py
from django import forms
from .models import *
from account.forms import FormSettings
from datetime import datetime


class VoterForm(FormSettings):
    ACADEMIC_LEVEL_CHOICES = [(str(i), f'Level {i}') for i in range(1, 6)]

    class Meta:
        model = Voter
        fields = ['phone', 'photo', 'date_of_birth', 'address', 'gender', 'department', 'academic_level']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['photo'].widget.attrs.update({'class': 'form-control'})
        self.fields['photo'].required = True
        self.fields['date_of_birth'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_of_birth'].required = True
        self.fields['address'].widget.attrs.update({'class': 'form-control', 'rows': '3'})
        self.fields['address'].required = True
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].required = True
        self.fields['department'].widget.attrs.update({'class': 'form-control'})
        self.fields['department'].required = True
        self.fields['academic_level'].widget.attrs.update({'class': 'form-control'})
        self.fields['academic_level'].choices = self.ACADEMIC_LEVEL_CHOICES
        self.fields['academic_level'].required = True
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].required = True

    def clean(self):
        cleaned_data = super().clean()
        date_of_birth = cleaned_data.get('date_of_birth')
        if date_of_birth:
            # Check if date is in the past
            if date_of_birth > datetime.now().date():
                self.add_error('date_of_birth', 'Date of birth cannot be in the future')
        return cleaned_data


class PositionForm(FormSettings):
    class Meta:
        model = Position
        fields = ['name', 'max_vote']


class CandidateForm(FormSettings):
    class Meta:
        model = Candidate
        fields = ['fullname', 'bio', 'position', 'photo']

account/views.py
from django.shortcuts import render, redirect, reverse, resolve_url
from django.http import JsonResponse, HttpResponseRedirect
from .email_backend import EmailBackend
from django.contrib import messages
from .forms import CustomUserForm
from voting.forms import VoterForm
from django.contrib.auth import login, logout
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings

# Create your views here.


def account_login(request):
    # If user is already logged in, redirect to appropriate dashboard
    if request.user.is_authenticated:
        if request.user.user_type == '1':
            return redirect('administrator:adminDashboard')
        else:
            return redirect('voting:voterDashboard')

    context = {}
    next_url = request.GET.get('next', '')
    
    # Prevent redirect loops by checking if next is a login URL
    if next_url and (next_url == reverse('account:login') or next_url.startswith(reverse('account:login') + '?')):
        next_url = ''
    
    if request.method == 'POST':
        user = EmailBackend.authenticate(
            request, 
            username=request.POST.get('email'), 
            password=request.POST.get('password')
        )
        
        if user is not None:
            login(request, user)
            post_next = request.POST.get('next', '')
            
            # Determine the best redirect URL
            if post_next and post_next != reverse('account:login') and not post_next.startswith(reverse('account:login') + '?'):
                next_url = post_next
            elif next_url and next_url != reverse('account:login') and not next_url.startswith(reverse('account:login') + '?'):
                next_url = next_url
            else:
                next_url = None
            
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                if next_url:
                    return JsonResponse({'redirect': next_url})
                if user.user_type == '1':
                    return JsonResponse({'redirect': reverse('administrator:adminDashboard')})
                else:
                    return JsonResponse({'redirect': reverse('voting:voterDashboard')})
            else:
                if next_url:
                    return redirect(next_url)
                if user.user_type == '1':
                    return redirect('administrator:adminDashboard')
                else:
                    return redirect('voting:voterDashboard')
        else:
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'error': 'Invalid email or password'}, status=400)
            else:
                messages.error(request, "Invalid email or password")
    
    # For GET requests, include the 'next' parameter in the context
    context['next'] = next_url
    return render(request, "voting/login.html", context)


def account_register(request):
    userForm = CustomUserForm(request.POST or None)
    voterForm = VoterForm(request.POST or None, request.FILES or None)
    context = {
        'form1': userForm,
        'form2': voterForm
    }
    
    if request.method == 'POST':
        if userForm.is_valid() and voterForm.is_valid():
            user = userForm.save(commit=False)
            voter = voterForm.save(commit=False)
            voter.admin = user
            user.save()
            voter.save()
            
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({
                    'status': 'success',
                    'message': 'Account created successfully! You can now log in.'
                })
            
            messages.success(request, "Account created successfully! You can now log in.")
            return redirect('account:login')
        else:
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({
                    'status': 'error',
                    'message': 'Form validation failed',
                    'errors': {
                        'user_form': userForm.errors,
                        'voter_form': voterForm.errors
                    }
                }, status=400)
            
            messages.error(request, "Provided data failed validation")
            return render(request, "voting/register.html", context)

    return render(request, "voting/register.html", context)


def account_logout(request):
    user = request.user
    if user.is_authenticated:
        logout(request)
        messages.success(request, "Thank you for visiting us!")
    else:
        messages.error(
            request, "You need to be logged in to perform this action")

    return redirect(reverse("account:login"))

account/templates/voting/register.html
{% extends 'root.html' %}
{% load static %}

{% block content %}
<section class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Register</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{% url 'account:register' %}" enctype="multipart/form-data" id="registerForm">
                            {% csrf_token %}
                            
                            {% if form1.errors or form2.errors %}
                                <div class="alert alert-danger">
                                    <strong>Form validation failed:</strong>
                                    <ul>
                                        {% for field in form1 %}
                                            {% for error in field.errors %}
                                                <li>{{ field.label }}: {{ error }}</li>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for field in form2 %}
                                            {% for error in field.errors %}
                                                <li>{{ field.label }}: {{ error }}</li>
                                            {% endfor %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                            
                            <h4>Account Information</h4>
                            <div class="form-group">
                                <label for="{{ form1.first_name.id_for_label }}">First Name</label>
                                {{ form1.first_name }}
                                <div id="{{ form1.first_name.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form1.last_name.id_for_label }}">Last Name</label>
                                {{ form1.last_name }}
                                <div id="{{ form1.last_name.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form1.email.id_for_label }}">Email</label>
                                {{ form1.email }}
                                <div id="{{ form1.email.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form1.password.id_for_label }}">Password</label>
                                {{ form1.password }}
                                <div id="{{ form1.password.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <hr>
                            <h4>Personal Information</h4>
                            
                            <div class="form-group">
                                <label for="{{ form2.phone.id_for_label }}">Phone</label>
                                {{ form2.phone }}
                                <div id="{{ form2.phone.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form2.photo.id_for_label }}">Photo</label>
                                {{ form2.photo }}
                                <div id="{{ form2.photo.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form2.date_of_birth.id_for_label }}">Date of Birth</label>
                                {{ form2.date_of_birth }}
                                <div id="{{ form2.date_of_birth.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form2.address.id_for_label }}">Address</label>
                                {{ form2.address }}
                                <div id="{{ form2.address.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form2.gender.id_for_label }}">Gender</label>
                                {{ form2.gender }}
                                <div id="{{ form2.gender.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form2.department.id_for_label }}">Department</label>
                                {{ form2.department }}
                                <div id="{{ form2.department.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <div class="form-group">
                                <label for="{{ form2.academic_level.id_for_label }}">Academic Level</label>
                                {{ form2.academic_level }}
                                <div id="{{ form2.academic_level.id_for_label }}_errors" class="text-danger"></div>
                            </div>
                            
                            <button type="submit" class="btn btn-primary btn-block">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block custom_js %}
<script>
$(document).ready(function() {
    // Initialize date picker
    $('#id_date_of_birth').datepicker({
        autoclose: true,
        format: 'yyyy-mm-dd',
        endDate: '0d',  // Prevent future dates
        orientation: 'bottom auto'
    });

    // Handle form submission
    $('#registerForm').on('submit', function(e) {
        e.preventDefault();
        var formData = new FormData(this);
        
        // Clear previous errors
        $('.text-danger').html('');
        $('.is-invalid').removeClass('is-invalid');
        
        $.ajax({
            url: '{% url "account:register" %}',
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'X-Requested-With': 'XMLHttpRequest'
            },
            success: function(response) {
                if (response.status === 'success') {
                    // Show success message
                    alert('Account created successfully! You can now log in.');
                    // Redirect to login page
                    window.location.href = '{% url "account:login" %}';
                } else {
                    // Show form errors
                    if (response.errors) {
                        // Handle user form errors
                        if (response.errors.user_form) {
                            for (var field in response.errors.user_form) {
                                var error = response.errors.user_form[field][0];
                                $('#' + field + '_errors').html('<span class="text-danger">' + error + '</span>');
                                $('#id_' + field).addClass('is-invalid');
                            }
                        }
                        // Handle voter form errors
                        if (response.errors.voter_form) {
                            for (var field in response.errors.voter_form) {
                                var error = response.errors.voter_form[field][0];
                                $('#' + field + '_errors').html('<span class="text-danger">' + error + '</span>');
                                $('#id_' + field).addClass('is-invalid');
                            }
                        }
                    }
                    if (response.message) {
                        alert('Error: ' + response.message);
                    }
                }
            },
            error: function(xhr, status, error) {
                console.error('Error:', error);
                console.error('Response:', xhr.responseText);
                try {
                    var response = JSON.parse(xhr.responseText);
                    if (response.message) {
                        alert('Error: ' + response.message);
                    }
                } catch (e) {
                    alert('An error occurred while processing your request. Please try again.');
                }
            }
        });
    });
});
</script>
{% endblock custom_js %}